# Lines starting with # are comments
# Syntax of a typical rule:

# target: prerequisites
# <TAB>recipe

# Usage:
# make 				# only execute the first target by default
# make say_hello	# execute a specific target
say_hello:
	echo "Hello World"

# To suppress echoing the actual command, use @echo
# Usage:
# make just_say_hello
just_say_hello:
	@echo "Hello World"
